apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: couchbase
    role: gateway
  name: sync-gateway
spec:
  replicas: 1
  selector:
    name: couchbase
    role: gateway
  template:
    metadata:
      labels:
        name: couchbase
        role: gateway
    spec:
      volumes:
      - name: config-mount
        configMap:
          name: sync-gateway-configmap
      imagePullSecrets:
      -  name: vxp-artifactory
      containers:
        - name: sync-gateway
          image: couchbase/sync-gateway
          #command: ["sync_gateway /home/sync_gateway/sync-gateway-config.json"]
          env:
          - name: SYNC_GATEWAY_CONFIG
            value: /home/sync_gateway/sync-gateway-config.json
          command: ["sync_gateway"]
          args: ["$(SYNC_GATEWAY_CONFIG)"]
#                configMapKeyRef:
#                  name: sync-gateway-configmap
#                  key: sync-gateway-configmap.yml
          volumeMounts:
          - name: config-mount
            mountPath: /home/sync_gateway
          ports:
            - containerPort: 4984
            - containerPort: 4985