apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-09-13T08:03:08Z
  labels:
    kops.k8s.io/cluster: depositinternal.k8s.local
  name: master-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20160830
  machineType: r4.xlarge
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1c