apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: es-data1-elasticsearch-1
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 1Gi
 storageClassName: gluster-heketi-external