apiVersion: v1
kind: LimitRange
metadata:
  name: quota-demo
spec:
  limits:
  - max:
      cpu: 0.1
      memory: 500Mi
    min:
      cpu: 0.05
      memory: 100Mi
    default:
      memory: 300Mi
    defaultRequest:
      memory: 200Mi
    type: Container
