apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: visitor-service
  name: visitor-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: visitor-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: visitor-service
    spec:
      containers:
      - image: gcr.io/google_containers/hpa-example
        imagePullPolicy: Always
        name: visitor-service
        ports:
        - containerPort: 80
          protocol: TCP
