apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: elasticlogs1-elasticsearch-2
spec:
 accessModes:
  - ReadWriteOnce
 resources:
   requests:
     storage: 100Mi
 storageClassName: fast-rbd
